### ISSUE TITLE
"Waiting for MySQL to be ready..."

### ISSUE THREAD

**Issue by RK-ITV** [CamprGmbH/on-premise#5]
Hello,
I don't know where I am at my current situation to use CAMPR. I receive some errors and it doesn't works.

### **Enviorment:**
- VirtaulBox with Ubuntu ("Ubuntu 20.04.2 LTS")
- docker (20.10.7) and docker-compose (1.25.0) 

### **Expected behavior:**
After the installation like wise described in the "README.md" I changed the setting in the "/etc/hosts" and the "parameters.yml" for the domain. After that I assumed that the service sould be reachable.

### **Actual behavior:**
After the installation I tried to start the docker containers. But I received no response on the website over the IP or the DNS name (camper.fritzbox).
![grafik](https://user-images.githubusercontent.com/36906982/121212084-53f58a80-c87d-11eb-941f-e49619f90f25.png)

My first thought was that I customized something false. But if I tried to check the other services "schickling/mailcatcher" or "mysql" over the ports `1080 `and `3306` they respond.

![grafik](https://user-images.githubusercontent.com/36906982/121208396-51456600-c87a-11eb-8df6-56a1291a86e1.png)
![grafik](https://user-images.githubusercontent.com/36906982/121211126-8652b800-c87c-11eb-8b53-b4d9c1c2cd1e.png)

Also to create a user/password over "docker-compose exec workspaces bash ..." failed. The same error appears in the logs after I start the docker containers.

`root@cc361057852c:/app# bin/console tss:app:user-create yourname@youremail.xxx admin admin --role=ROLE_ADMIN`
`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Redis" from the global namespace.`
`Did you forget a "use" statement for "Enqueue\Redis\Redis"? in /app/backend/vendor/enqueue/redis/PhpRedis.php:67`
`Stack trace:`
`#0 /app/backend/vendor/enqueue/redis/RedisConnectionFactory.php(106): Enqueue\Redis\PhpRedis->connect()`
`#1 /app/backend/vendor/enqueue/redis/RedisConnectionFactory.php(77): Enqueue\Redis\RedisConnectionFactory->createRedis()`
`#2 /app/var/cache/prod/appProdProjectContainer.php(3715): Enqueue\Redis\RedisConnectionFactory->createContext()`
`#3 /app/backend/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(274): appProdProjectContainer->getEnqueue_Transport_DefaultRedis_ContextService()`
`#4 /app/var/cache/prod/appProdProjectContainer.php(3793): Symfony\Component\DependencyInjection\Container->get('enqueue.transpo...')`
`#5 /app/backend/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(274): appProdProjectContainer- in /app/backend/vendor/enqueue/redis/PhpRedis.php on line 67`
` `
`Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Redis" from the global namespace.`
`Did you forget a "use" statement for "Enqueue\Redis\Redis"? in /app/backend/vendor/enqueue/redis/PhpRedis.php:67`
`Stack trace:`
`#0 /app/backend/vendor/enqueue/redis/RedisConnectionFactory.php(106): Enqueue\Redis\PhpRedis->connect()`
`#1 /app/backend/vendor/enqueue/redis/RedisConnectionFactory.php(77): Enqueue\Redis\RedisConnectionFactory->createRedis()`
`#2 /app/var/cache/prod/appProdProjectContainer.php(3715): Enqueue\Redis\RedisConnectionFactory->createContext()`
`#3 /app/backend/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(274): appProdProjectContainer->getEnqueue_Transport_DefaultRedis_ContextService()`
`#4 /app/var/cache/prod/appProdProjectContainer.php(3793): Symfony\Component\DependencyInjection\Container->get('enqueue.transpo...')`
`#5 /app/backend/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(274): appProdProjectContainer- in /app/backend/vendor/enqueue/redis/PhpRedis.php on line 67`

### Logs from docker containers:
[campr - container logs.txt](https://github.com/Campr-Project-Management/on-premise/files/6617609/campr.-.container.logs.txt)

Is this a bug or just a poor configuration resulted of my skills?
I am thankful for every hint to solve this error.

Thank you.

**Comment by zeGzD** [comment]
I just encountered the same issue.

Could we please have some support on solving this problem?

Thank you.
